### ISSUE TITLE
Polymer build fails

### ISSUE THREAD

**Issue by MarcusMorba** [vaadin/generator-polymer-init-vaadin-elements-app#30]
I followed the  manual, but it fails with errors. E.g. "Promise rejection: Error: Could not load @vaadin/vaadin-grid/vaadin-grid.js"

**Comment by web-padawan** [comment]
Sorry about not answering earlier. Could you provide a version of Polymer CLI that you are using, and a complete output? Also, the `package.json` of the generated project would be nice to see.

**Comment by web-padawan** [comment]
We are about to archive this repo. See the following repo for working setup:

https://github.com/web-padawan/polymer3-webpack-starter
