### ISSUE TITLE
Minor fixes for instructions

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/generator-polymer-init-vaadin-elements-app#41]
Several minor things to fix:

1. `vaadin-lumo-styles` version conflict during automated bower installation: 
<img width="848" alt="Screenshot 2019-08-09 at 10 41 59" src="https://user-images.githubusercontent.com/29372419/62762915-e9157580-ba92-11e9-8ccd-0a3a7b18f59c.png">

2. By default port should be `8081` not `8080` over here: 
https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/master/app/templates/README.md#start-the-development-server

3. `fragments` in `polymer.json` are not set for existing views, so can be confusing for the user where new views should be added:
https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/master/app/templates/README.md#adding-a-new-view

4. Probably we should replace `polymer test --npm` with `npm test` as specified in the main README file because it produces errors:
https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/master/app/templates/README.md#run-tests
<img width="895" alt="Screenshot 2019-08-09 at 11 00 30" src="https://user-images.githubusercontent.com/29372419/62763821-1fec8b00-ba95-11e9-8a1e-bc79eb9e752e.png">

**Comment by web-padawan** [comment]
Closing as the repo is to be archived soon and no longer present at https://vaadin.com/start
